## stock download

In [ ]:
!pip install yahoo_fin

Requirement already satisfied: yahoo_fin in /usr/local/lib/python3.11/dist-packages (0.8.9.1)
Requirement already satisfied: requests-html in /usr/local/lib/python3.11/dist-packages (from yahoo_fin) (0.10.0)
Requirement already satisfied: feedparser in /usr/local/lib/python3.11/dist-packages (from yahoo_fin) (6.0.11)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from yahoo_fin) (2.32.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from yahoo_fin) (2.2.2)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.11/dist-packages (from feedparser->yahoo_fin) (1.0.0)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas->yahoo_fin) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->yahoo_fin) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->yahoo_fin) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->yahoo_fin) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->yahoo_fin) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->yahoo_fin) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->yahoo_fin) (2025.1.31)
Requirement already satisfied: pyquery in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (2.0.1)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (2.0.3)
Requirement already satisfied: parse in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (1.20.2)
Requirement already satisfied: bs4 in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (0.0.2)
Requirement already satisfied: w3lib in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (2.3.1)
Requirement already satisfied: pyppeteer>=0.0.14 in /usr/local/lib/python3.11/dist-packages (from requests-html->yahoo_fin) (2.0.0)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.11/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.11/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (8.6.1)
Requirement already satisfied: pyee<12.0.0,>=11.0.0 in /usr/local/lib/python3.11/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (11.1.1)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.67.1)
Requirement already satisfied: websockets<11.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (10.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->yahoo_fin) (1.17.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4->requests-html->yahoo_fin) (4.13.3)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.11/dist-packages (from pyquery->requests-html->yahoo_fin) (5.3.1)
Requirement already satisfied: cssselect>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from pyquery->requests-html->yahoo_fin) (1.2.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.21.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from pyee<12.0.0,>=11.0.0->pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4->requests-html->yahoo_fin) (2.6)

# Sentiment Analysis

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import pandas as pd
from IPython.display import display

# Update with the correct path after finding the shared folder
base_dir = "/content/drive/MyDrive/Advanced NLP/Assignments/Assignment_2/filings/fillings"
cik_number = "0000798354"
company_dir = os.path.join(base_dir, cik_number)

# Initialize an empty list to store data
risk_data = []

# Loop through all year directories
if os.path.exists(company_dir):
    for year in sorted(os.listdir(company_dir)):  # Sorting ensures chronological order
        year_path = os.path.join(company_dir, year)
        risk_file = os.path.join(year_path, "risk_factors.txt")

        # Check if the directory is a year and risk_factors.txt exists
        if os.path.isdir(year_path) and os.path.exists(risk_file):
            with open(risk_file, "r", encoding="utf-8") as file:
                risk_text = file.read().strip()  # Read and clean text

            # Append to list
            risk_data.append({"Year": int(year), "Risk Factors": risk_text})

# Convert to DataFrame
df_risks = pd.DataFrame(risk_data)

# Display the collected risk factor data
display(df_risks)

    Year                                       Risk Factors
0   2006  Item 1A. Risk Factors \n You should carefully ...
1   2007  Item 1A. Risk Factors \n You should carefully ...
2   2009  Item 1A. Risk Factors \n You should carefully ...
3   2010  Item 1A. Risk Factors \n You should carefully ...
4   2011  Item 1A. Risk Factors \n You should carefully ...
5   2012  Item 1A.   Risk Factors\n---------------------...
6   2013  Item 1A. Risk Factors \n You should carefully ...
7   2014  Item 1A. Risk Factors \n You should carefully ...
8   2015  Item 1A.  Risk Factors \n You should carefully...
9   2016  Item 1A.  Risk Factors\nYou should carefully c...
10  2017  Item 1A.  Risk Factors\nYou should carefully c...
11  2018  Item 1A.  Risk Factors\nYou should carefully c...
12  2019  Item 1A.  Risk Factors\nYou should carefully c...
13  2020  Item 1A.  Risk Factors\nYou should carefully c...
14  2021  Item 1A.  Risk Factors\nYou should carefully c...
15  2022  Item 1A.  Risk Factors\nYou should carefully c...
16  2023  Item 1A.  Risk Factors\nYou should carefully c...
17  2024  Item 1A.  Risk Factors\nYou should carefully c...

In [ ]:
# Select the raw risk factors text for 2022
raw_text_2022 = df_risks[df_risks["Year"] == 2022]["Risk Factors"].values[0]
raw_text_2023 = df_risks[df_risks["Year"] == 2023]["Risk Factors"].values[0]

In [ ]:
raw_text_2023

'Item 1A.  Risk Factors\nYou should carefully consider each of the risks described below, together with all of the other information contained in this Annual Report on Form 10-K, before making an investment decision with respect to our securities. If any of the following risks develop into actual events, our business, results of operations or financial condition could be materially and adversely affected, and you may lose all or part of your investment.\nCompetitive and Business Risks\nWe operate in a competitive business environment and may not be able to compete effectively.\nThe markets for our products and services are highly competitive from new and existing competitors. Our principal competitors include other vendors and providers of financial services technology and payment systems, data processing affiliates of large companies, processing centers owned or operated as user cooperatives, financial institutions, independent sales organizations (“ISOs”), independent software vendors, payments companies and payment network operators. Our competitors vary in size and in the scope and breadth of the services they offer. Many of our larger existing and potential clients have historically developed their key applications in-house. As a result, we may compete against our existing or potential clients’ in-house capabilities. In addition, we expect that the markets in which we compete will continue to attract new technologies and well-funded competitors, including large technology, telecommunication, media and other companies not historically in the financial services and payments industries, start-ups and international providers of products and services similar to ours. In addition, participants in the financial services, payments and technology industries may merge, create joint ventures or engage in other business combinations, alliances and consolidations that may strengthen their existing products and services or create new products and services that compete with ours. We cannot provide any assurance that we will be able to compete successfully against current or future competitors or that competitive pressures faced by us in the markets in which we operate will not materially and adversely affect our business, results of operations and financial condition.\nIf we fail to keep pace with technological change, we could lose clients or have trouble attracting new clients, and our ability to grow may be limited.\nThe markets for our products and services are characterized by constant and rapid technological change, evolving industry standards, frequent introduction of new products and services, and increasing client expectations. Our ability to respond timely to these changes, including by enhancing our current products and services and developing and introducing new products and services, will significantly affect our future success. In addition, the success of certain of our products and services rely, in part, on financial institutions, business partners and other third parties promoting the use of or distributing our products and services. If we are unsuccessful in developing, marketing and selling products or services that gain market acceptance, or if third parties \n \ninsufficiently promote or distribute our products and services, it would likely have a material adverse effect on our ability to retain existing clients, to attract new ones and to grow profitably.\nIf we are unable to renew contracts on favorable terms or if contracts are terminated prematurely, we could lose clients and our results of operations and financial condition may be adversely affected.\nFailure to achieve favorable renewals of client contracts could negatively impact our business. At the end of the contract term, clients have the opportunity to renegotiate their contracts with us or to consider whether to engage one or more of our competitors to provide products and services or to perform the services in-house. Some of our competitors may offer more attractive prices, features or other services that we do not offer, and some clients may desire to perform the services themselves. Larger clients may be able to seek lower prices from us when they renew or extend a contract or the client’s business has significant volume changes. In addition, larger clients may reduce the services we provide if they decide to move services in-house. Further, our small merchant business clients may seek reduced fees due to pricing competition, their own financial condition or pressure from their customers. \nWe also have contracts with U.S. federal, state and local governments. The contracts with these clients may contain terms that are not typical for non-government clients, such as the right to terminate for convenience, the right to unilaterally modify or reduce work to be provided under the contract, significant or unlimited indemnification obligations and being subject to appropriation of funds for the government contract program. In addition, if any of our government contracts were to be terminated for default, we could be suspended or debarred from contracting with that entity in the future, which could also provide other government clients the right to terminate.\nThese factors could result in lower revenue from a client than we had anticipated based on our agreement with that client. If we are not successful in achieving high contract renewal rates and favorable contract terms, if contracts are terminated, or if we are prevented from performing work for these clients in the future, our results of operations and financial condition may be materially and adversely affected.\nOur business depends, in part, on our merchant relationships and alliances, and if we are unable to maintain these relationships and alliances, our business may be adversely affected.\nUnder our alliance program, a bank or other institution forms an alliance with us, generally on an exclusive basis, either contractually or through a separate legal entity. Merchant contracts may be contributed to the alliance by us and/or the bank or institution. The banks and other institutions generally provide card association sponsorship, clearing and settlement services and typically act as a merchant referral source when the institution has an existing banking or other relationship with such merchant. We provide transaction processing and related functions to the alliance. Both we and our alliance partners may also provide management, sales, marketing and other administrative services. The alliance structure allows us to be the processor for multiple financial institutions, any one of which may be selected by the merchant as its bank partner. Our merchant acquiring business depends, in part, on our merchant relationships, alliances and other distribution channels. There can be no guarantee that we will achieve growth in our merchant relationships, alliances or other distribution channels. In addition, our contractual arrangements with merchants and merchant alliance partners are for fixed terms and may allow for early termination upon the occurrence of certain events. There can be no assurance that we will be able to renew our contractual arrangements with these merchants or merchant alliance partners on similar terms or at all. The loss of merchant relationships or alliance partners could negatively impact our business and have a material adverse effect on our results of operations and financial condition.\nThe ongoing COVID-19 pandemic has had, and may continue to have, adverse impacts on our business and may amplify many of our other known risks.\nThe ongoing COVID-19 pandemic and the related government actions taken to prevent the spread of COVID-19 have increased economic uncertainty and financial market volatility and caused a decline in consumer and business confidence, and could further negatively impact the demand for our products and services, including merchant acquiring and payment processing. Ultimately, the extent of the adverse impact of the COVID-19 pandemic on our business, results of operations, liquidity and financial condition will depend on, among other matters, the duration and intensity of the pandemic; the level of success of global vaccination efforts; governmental and private sector responses to the pandemic and the impact of such responses on us; and the impact of the pandemic on our employees, clients, vendors, supply chain, operations and sales, all of which are uncertain, difficult to predict and may remain prevalent for a significant period of time even after the pandemic subsides. These and other potential negative impacts relating to the COVID-19 pandemic may also heighten or exacerbate the other risk factors described in this Annual Report on Form 10-K.\n \nChanges in card association and debit network fees or products could increase costs or otherwise limit our operations.\nFrom time to time, card associations and debit networks, including the card networks which we own and operate, increase the processing and other fees (including what is commonly called “interchange fees”) that they charge. It is possible that competitive and other pressures will result in us absorbing a portion of such increases in the future, or not being able to increase our own fees, which would increase our operating costs, reduce our profit margin, limit our growth, and adversely affect our business, results of operations and financial condition. In addition, the various card associations and networks prescribe certain capital requirements. Any increase in the capital level required would further limit our use of capital for other purposes.\nConsolidations in the banking and financial services industry could adversely affect our revenue by eliminating existing or potential clients and making us more dependent on fewer clients.\nMergers, consolidations and failures of financial institutions reduce the number of our clients and potential clients, which could adversely affect our revenue. If our clients merge with or are acquired by other entities that are not our clients, or that use fewer of our services, they may discontinue or reduce their use of our services. Our alliance strategy could also be negatively affected by consolidations, especially where the financial institutions involved are committed to their internal merchant processing businesses that compete with us. It is also possible that the larger financial institutions that result from mergers or consolidations could have an increased ability to negotiate terms with us or could decide to perform in-house some or all of the services which we currently provide or could provide. Any of these developments could have a material adverse effect on our business, results of operations and financial condition.\nOperational and Security Risks\nSecurity incidents or other technological risks involving our systems and data, or those of our clients, partners or vendors, could expose us to liability or damage our reputation.\nOur operations depend on receiving, storing, processing and transmitting sensitive information pertaining to our business, our employees, our clients and their customers. Under the card network rules, various federal, state and international laws, and client contracts, we are responsible for information provided to us by financial institutions, merchants, ISOs, third-party service providers and others. Preserving the confidentiality of sensitive business and personal information is critical to our business. Any unauthorized access, intrusion, infiltration, network disruption, ransom, denial of service or similar incident could disrupt the integrity, continuity, security and trust of our systems or data, or the systems or data of our clients, partners or vendors. These incidents are often difficult to detect and are constantly evolving. We expect that unauthorized parties will continue to attempt to gain access to our systems or facilities, and those of our clients, partners and vendors, through various means and with increasing sophistication, particularly as cybercriminals attempt to profit from increased online banking, e-commerce and other online activity. These events could create costly litigation, significant financial liability, increased regulatory scrutiny, financial sanctions and a loss of confidence in our ability to serve clients and cause current or potential clients to choose another service provider, all of which could have a material adverse impact on our business. In addition, we expect to continue to invest significant resources to maintain and enhance our information security and controls or to investigate and remediate any security vulnerabilities. Although we believe that we maintain a robust program of information security and controls and that none of the events that we have encountered to date have materially impacted us, we cannot be certain that the security measures and procedures we have in place to detect security incidents and protect sensitive data, including protection against unauthorized access and use by our employees, will be successful or sufficient to counter all current and emerging risks and threats. The impact of a material event involving our systems and data, or those of our clients, partners or vendors, could have a material adverse effect on our business, results of operations and financial condition.\nOperational failures and resulting interruptions in the availability of our products or services could harm our business and reputation.\nOur business depends heavily on the reliability of our systems. An operational failure that results in an interruption in the availability of our products and services could harm our business or cause us to lose clients. An operational failure could involve the hardware, software, data, networks or systems upon which we rely to deliver our services and could be caused by our actions, the actions of third parties or events over which we may have limited or no control. Events that could cause operational failures include, but are not limited to, hardware and software defects or malfunctions, ransomware, denial-of-service and other cyberattacks, human error, earthquakes, hurricanes, floods, fires, natural disasters, pandemics, power losses, disruptions in telecommunications services, fraud, military or political conflicts, terrorist attacks, computer viruses or other malware, or other events. In the event of operational failures or damage or disruption to our business due to these occurrences, we may not be able to successfully or quickly recover all of our critical business functions, assets and data through our business continuity program. Implementation delays, interruptions of service or hardware device defects could damage our relationship with clients and could cause us to incur substantial expenses, including those related to the payment of service credits, product recalls or other liabilities. A prolonged interruption of our services or network could cause us to experience data loss or a \n \nreduction in revenue, and significantly impact our clients’ businesses and the customers they serve. In addition, a significant interruption of service or product recall could have a negative impact on our reputation and could cause our current and potential clients to choose another service provider. As a provider of payments solutions and other financial services, clients, regulators and others may require enhanced business continuity and disaster recovery plans including frequent testing of such plans. Meeting these various requirements may require a significant investment of time and money. Any of these developments could have a material adverse impact on our business, results of operations and financial condition.\nDisruptions of operations of other participants in the global financial system could prevent us from delivering our products and services.\nThe operations and systems of many participants in the global financial system are interconnected. Many of the transactions involving our products and services rely on multiple participants in the global financial system to move funds and communicate information to the next participant in the transaction chain. A disruption for any reason of the operations of a participant in the global financial system could impact our ability to obtain or provide information or cause funds to be moved in a manner to successfully deliver our products and services. Although we work with other participants to avoid any disruptions, there is no assurance that such efforts will be effective. Such a disruption could lead to our inability to deliver products and services, reputational damage, lost clients and revenue, loss of clients’ and their customers’ confidence, as well as additional costs, all of which could have a material adverse effect on our business, results of operations and financial condition.\nWe rely on third parties to provide products and services and if we are unable to obtain such products or services in the future or if these third parties fail to perform these services adequately, our business may be materially and adversely affected.\nWe rely on third parties we do not control to provide us with products and services, including payment card networks, acquiring processors, payment card issuers, financial institutions and the Automated Clearing House (“ACH”) network which transmit transaction data, process chargebacks and refunds, and perform clearing services in connection with our settlement activities. If, for example, such third parties stop providing clearing services or limit our volumes, we would need to find other financial institutions to provide those services. In the event these third parties fail to provide these services adequately or in a timely manner, including as a result of errors in their systems or events beyond their control, or refuse to provide these services on terms acceptable to us or at all, and we are not able to find timely suitable alternatives, we may no longer be able to provide certain services to customers, which could expose us and our clients to information security, financial, compliance and reputational risks. We may be negatively impacted by a disruption to our supply chain or third-party delivery service providers, including if the factories that manufacture our point-of-sale devices, payment cards or computer chips for payment cards, or paper stock are temporarily closed or experience workforce shortages; shipping services are interrupted or delayed; there are increased lead times, shortages or higher costs for certain materials and components; or there are workforce shortages at our third-party customer support, software development or technology hosting facilities. If we are unable to renew our existing contracts with key vendors and service providers, we might not be able to replace the related product or service at all or at the same cost. Any of these risks could have a material adverse effect on our business, results of operations and financial condition.\nWe may experience software defects, development delays or installation difficulties, which would harm our business and reputation and expose us to potential liability.\nOur services are based on sophisticated software and computer systems and we may encounter delays when developing new applications and services. Further, the software underlying our services may contain undetected errors or defects when first introduced or when new versions are released. We may also experience difficulties in installing or integrating our technology on systems or with other programs used by our clients. Defects in our software, errors or delays in the processing of electronic transactions or other difficulties could result in interruption of business operations, delay in market acceptance, additional development and remediation costs, diversion of technical and other resources, loss of clients or client data, n

In [ ]:

# Create a DataFrame with the variable name as the column name and the text as its value
import pandas as pd

# Sample text data
text1 = raw_text_2022

text2 = raw_text_2023


# Create a DataFrame
df = pd.DataFrame(
    [{"title": "raw_text_2022", "text": text1},
     {"title": "raw_text_2023", "text": text2}]
)

print(df)


# Display the DataFrame
#print(df)
#df[raw_text_2022]
# Save the DataFrame to a CSV file (optional)
#df.to_csv('my_text_data.csv', index=False)

           title                                               text
0  raw_text_2022  Item 1A.  Risk Factors\nYou should carefully c...
1  raw_text_2023  Item 1A.  Risk Factors\nYou should carefully c...

# Dictionary

In [ ]:
with open("stopwords.txt", "r") as f:
    stopwords = f.read().split("\n")[:-1]
stopwords[:10]

['ABOUT', 'ABOVE', 'AFTER', 'AGAIN', 'ALL', 'AM', 'AMONG', 'AN', 'AND', 'ANY']

In [ ]:
def preprocess_text(text):
    words = text.split()
    words = [w.lower() for w in words]
    words = [w for w in words if w not in stopwords]
    # Remove punctuation and numbers
    words = [w for w in words if w.isalpha()]
    return " ".join(words)

df["text_clean"] = df["text"].apply(preprocess_text)
df

,title,text,text_clean
0,raw_text_2022,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...
1,raw_text_2023,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...

In [ ]:
df["text_clean"][0]

'item risk factors you should carefully consider each of the risks described together with all of the other information contained in this annual report on form before making an investment decision with respect to our if any of the following risks develop into actual our results of operations or financial condition could be materially and adversely and you may lose all or part of your competitive and business risks the ongoing pandemic has and may continue to adverse impacts on our business and may amplify many of our other known in response to the the governments of many cities and other geographic regions have taken actions to prevent the spread of such as imposing travel restrictions and social distancing or orders and other similar these measures among other negatively impacted consumer and business spending as a our operating primarily within our merchant acquiring and which earn the pandemic has negatively impacted and may continue to negatively transaction create economic uncertainty and financial market reduce economic increase unemployment and cause a decline in consumer and business and could in the future further negatively impact the demand for our products and including merchant acquiring and payment the extent of the adverse impact of the pandemic on our results of liquidity and financial condition will depend among other the duration and intensity of the the level of success of global vaccination governmental and private sector responses to the pandemic and the impact of such responses on and the impact of the pandemic on our supply operations and all of which are difficult to predict and may remain prevalent for a significant period of time even after the pandemic including due to a continued or prolonged recession in the or other major additional factors that could negatively impact us increases in consumer chargebacks associated with processed transactions that merchant clients have submitted but have not fulfilled as an unprecedented number of merchants have been required to suspend or terminate their merchants may be unable to fund these potentially resulting in losses to to our supply chain and delivery service including the factories that manufacture our payment cards or computer chips for payment or paper stock are temporarily closed or experience workforce shipping services are interrupted or there are increased lead shortages or higher costs for certain materials and or there are workforce shortages at our or customer software development or technology hosting orders or other restrictions that limit or prohibit us from providing services from regular service the failure of our business continuity or supply chain issues that prevent us from meeting client service any of which may increase the risk of failing to meet client contractual obligations that could cause loss of contractual penalties or potential legal may require additional time to pay us or fail to pay us at which could significantly increase the amount of accounts receivable and require us to record additional allowances for doubtful if clients cease operations or file for bankruptcy we may experience lower revenue and earnings and have greater exposure to future transaction and possibility of one or more clusters of cases occurring at our production or operations affecting our employees or affecting the systems or employees of our clients or other third parties on which we the pandemic has caused us to modify our business including restricting limiting visitors to our disinfecting providing onsite testing and personal protective equipment to establishing a variety of safety protocols at facilities and requiring employees to be fully vaccinated unless they have an approved or state we expect to continue such safety measures for the foreseeable future and may take further or adapt these existing as government authorities may require or recommend or as we may determine to be in the best interest of our clients and such measures may impact our productivity or and there is no certainty that such measures will be sufficient to mitigate the risks posed by the these and other potential negative impacts relating to the pandemic may also heighten or exacerbate the other risk factors described in this annual report on form we operate in a competitive business environment and may not be able to compete the markets for our products and services are highly competitive from new and existing our principal competitors include other vendors and providers of financial services technology and payment data processing affiliates of large processing centers owned or operated as user financial independent sales organizations independent software payments companies and payment network our competitors vary in size and in the scope and breadth of the services they many of our larger existing and potential clients have historically developed their key applications as a we may compete against our existing or potential in we expect that the markets in which we compete will continue to attract new technologies and including large media and other companies not historically in the financial services and payments and international providers of products and services similar to in participants in the financial payments and technology industries may create joint ventures or engage in other business alliances and consolidations that may strengthen their existing business services or create new payment services that compete with our we cannot provide any assurance that we will be able to compete successfully against current or future competitors or that competitive pressures faced by us in the markets in which we operate will not materially and adversely affect our results of operations and financial if we fail to keep pace with technological we could lose clients or have trouble attracting new and our ability to grow may be the markets for our products and services are characterized by constant and rapid technological frequent introduction of new products and and increasing client our ability to enhance our current products and services and to develop and introduce innovative products and services will significantly affect our future we may not be successful in marketing or selling new products and services that meet these demands or achieve market we must anticipate and respond to these changes in order to remain competitive within our relevant for our ability to provide innovative technology to our merchant clients could have an impact on our merchant acquiring and new services and technologies that we develop may be impacted by solutions and standards related to tokenization or other fraud prevention and security if we are unable to anticipate or respond to technological changes or evolving industry standards on a timely our ability to remain competitive could be materially adversely in the success of certain of our products and services in on financial corporate and other third parties to promote the use of our products and services by their if we are unsuccessful in offering products or services that gain market acceptance and compete or if third parties insufficiently promote our products and it would likely have a material adverse effect on our ability to retain existing to attract new ones and to grow if we are unable to renew client contracts at favorable we could lose clients and our results of operations and financial condition may be adversely failure to achieve favorable renewals of client contracts could negatively impact our at the end of the contract clients have the opportunity to renegotiate their contracts with us or to consider whether to engage one or more of our competitors to provide products and services or to perform the services some of our competitors may offer more attractive features or other services that we do not and some clients may desire to perform the services larger clients may be able to seek lower prices from us when they renew or extend a contract or the business has significant volume in larger clients may reduce the services we provide if they decide to move services our small merchant business clients may seek reduced fees due to pricing their own financial or pressures from their on some these factors result in lower revenue from a client than we had anticipated based on our previous agreement with that if we are not successful in achieving high renewal rates and favorable contract our results of operations and financial condition may be materially and adversely our business in on our merchant relationships and and if we are unable to maintain these relationships and our business may be adversely under our alliance a bank or other institution forms an alliance with generally on an exclusive either contractually or through a separate legal merchant contracts may be contributed to the alliance by us the bank or the banks and other institutions generally provide card association clearing and settlement services and typically act as a merchant referral source when the institution has an existing banking or other relationship with such we provide transaction processing and related functions to the both we and our alliance partners may also provide marketing and other administrative the alliance structure allows us to be the processor for multiple financial any one of which may be selected by the merchant as its bank our merchant acquiring business in on our merchant alliances and other distribution there can be no guarantee that we will achieve growth in our merchant alliances or other distribution in our contractual arrangements with merchants and merchant alliance partners are for fixed terms and may allow for early termination upon the occurrence of certain there can be no assurance that we will be able to renew our contractual arrangements with these merchants or merchant alliance partners on similar terms or at the loss of merchant relationships or alliance partners could negatively impact our business and have a material adverse effect on our results of operations and financial changes in card association and debit network fees or products could increase costs or otherwise limit our from time to card associations and debit including the card networks which we own and increase the processing and other fees what is commonly called that they it is possible that competitive and other pressures will result in us absorbing a portion of such increases in the or not being able to increase our own which would increase our operating reduce our profit limit our and adversely affect our results of operations and financial in the various card associations and networks prescribe certain capital any increase in the capital level required would further limit our use of capital for other consolidations in the banking and financial services industry could adversely affect our revenue by eliminating existing or potential clients and making us more dependent on fewer consolidations and failures of financial institutions reduce the number of our clients and potential which could adversely affect our if our clients merge with or are acquired by other entities that are not our or that use fewer of our they may discontinue or reduce their use of our our alliance strategy could also be negatively affected by especially where the financial institutions involved are committed to their internal merchant processing businesses that compete with it is also possible that the larger financial institutions that result from mergers or consolidations could have an increased ability to negotiate terms with us or could decide to perform some or all of the services which we currently provide or could any of these developments could have a material adverse effect on our results of operations and financial operational and security risks security incidents or other technological risks involving our systems and or those of our partners or could expose us to liability or damage our our operations depend on processing and transmitting sensitive information pertaining to our our our clients and their under the card network various state and international and client we are responsible for information provided to us by financial service providers and preserving the confidentiality of sensitive business and personal information is critical to our any unauthorized network denial of service or similar incident could disrupt the security and trust of our systems or or the systems or data of our partners or these incidents are often difficult to detect and are constantly we expect that unauthorized parties will continue to attempt to gain access to our systems or and those of our partners and through various means and with increasing particularly as cybercriminals attempt to profit from the disruption caused by the pandemic given increased online and other online these events could create costly significant financial increased regulatory financial sanctions and a loss of confidence in our ability to serve clients and cause current or potential clients to choose another service all of which could have a material adverse impact on our in we expect to continue to invest significant resources to maintain and enhance our information security and controls or to investigate and remediate any security although we believe that we maintain a robust program of information security and controls and that none of the events that we have encountered to date have materially impacted we cannot be certain that the security measures and procedures we have in place to detect security incidents and protect sensitive including protection against unauthorized access and use by our will be successful or sufficient to counter all current and emerging technological risks and the impact of a material event involving our systems and or those of our partners or could have a material adverse effect on our results of operations and financial operational failures and resulting interruptions in the implementation or availability of our products or services could harm our business and our business depends heavily on the reliability of our processing and other an operational failure and the resulting implementation delays or service interruption could harm our business or cause us to lose an operational failure could involve the networks or systems upon which we rely to deliver our services and could be caused by our the actions of third parties or events over which we may have limited or no events that could cause operational failures but are not limited hardware and software defects or computer and other human natural power disruptions in telecommunications military or political terrorist computer viruses or other or other in the event of operational failures or damage or disruption to our business due to these we may not be able to successfully or quickly recover all of our critical business assets and data through our business continuity implementation interruptions of service or hardware device defects could damage our relationship with clients and could cause us to incur substantial including those related to the payment of service product recalls or other a prolonged interruption of our services or network could cause us to experience data loss or a reduction in and significantly impact our businesses and the customers they in a significant implementation interruption of service or product recall could have a negative impact on our reputation and could cause our current and potential clients to choose another service as a provider of payments solutions and other financial regulators and others may require specific business continuity and disaster recovery plans including frequent testing of such meeting these various requirements may require a significant investment of time and any of these developments could have a material adverse impact on our results of operations and financial disruptions of operations of other participants in the global financial system could prevent us from delivering our products and the operations and systems of many participants in the global financial system are many of the transactions involving our products and services rely on multiple participants in the global financial system to move funds and communicate information to the next participant in the transaction a disruption for any reason of the operations of a participant in the global financial system could impact our ability to obtain or provide information or cause funds to be moved in a manner to successfully deliver our products and although we work with other participants to avoid any there is no assurance that such efforts will be such a disruption could lead to our inability to deliver products and reputational lost clients and loss of and their as well as additional all of which could have a material adverse effect on our results of operations and financial we rely on third parties to provide products and services and if we are unable to obtain such products or services in the future or if these third parties fail to perform these services our business may be materially and adversely we rely on third parties we do not control to provide us with products and including payment card acquiring payment card financial institutions and the automated clearing house network which transmit transaction process chargebacks and and perform clearing services in connection with our settlement for such third parties stop providing clearing services or limit our we would need to find other financial institutions to provide those in the event these third parties fail to provide these services adequately or in a timely including as a result of errors in their systems or events beyond their or refuse to provide these services on terms acceptable to us or at and we are not able to find timely suitable we may no longer be able to provide certain services to which could expose us and our clients to information compliance and reputational among and have a material adverse effect on our results of operations and financial in if we are unable to renew our existing contracts with key vendors and service we might not be able to replace the related product or service at all or at the same which would negatively impact our results of we may experience software development delays or installation which would harm our business and reputation and expose us to potential our services are based on sophisticated software and computer systems and we may encounter delays when developing new applications and the software underlying our services may contain undetected errors or defects when first introduced or when new versions are we may also experience difficulties in installing or integrating our technology on systems or with other programs used by our defects in our errors or delays in the processing of electronic transactions or other difficulties could result in interruption of business delay in market additional development and remediation diversion of technical and other loss of clients or client negative publicity or exposure to liability although we attempt to limit our potential liability through disclaimers and limitation of liability provisions in our license and client we cannot be certain that these measures will successfully limit our global market risks our business may be adversely affected by geopolitical and other risks associated with operations outside of the as we continue to expand we may incur higher than anticipated costs and may become more susceptible to these we offer merchant processing and issuing services outside of the including in the india and our facilities outside of the and those of our suppliers and including customer software development and technology hosting are subject to including natural public health political political instability and other events outside of our or our as we continue to expand internationally and grow our client base outside of the we may face challenges due to the presence of more estab

In [ ]:
lm_dict = pd.read_csv("Loughran-McDonald_MasterDictionary_1993-2023.csv")
lm_dict

,Word,Seq_num,Word Count,Word Proportion,Average Proportion,Std Dev,Doc Count,Negative,Positive,Uncertainty,Litigious,Strong_Modal,Weak_Modal,Constraining,Complexity,Syllables,Source
0,AARDVARK,1,664,2.690000e-08,1.860000e-08,4.050000e-06,131,0,0,0,0,0,0,0,0,2,12of12inf
1,AARDVARKS,2,3,1.210000e-10,8.230000e-12,9.020000e-09,1,0,0,0,0,0,0,0,0,2,12of12inf
2,ABACI,3,9,3.640000e-10,1.110000e-10,5.160000e-08,7,0,0,0,0,0,0,0,0,3,12of12inf
3,ABACK,4,29,1.170000e-09,6.330000e-10,1.560000e-07,28,0,0,0,0,0,0,0,0,2,12of12inf
4,ABACUS,5,9349,3.790000e-07,3.830000e-07,3.460000e-05,1239,0,0,0,0,0,0,0,0,3,12of12inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86548,ZYGOTE,86529,69,2.790000e-09,1.310000e-09,2.940000e-07,45,0,0,0,0,0,0,0,0,2,12of12inf
86549,ZYGOTES,86530,1,4.050000e-11,1.720000e-11,1.880000e-08,1,0,0,0,0,0,0,0,0,2,12of12inf
86550,ZYGOTIC,86531,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,0,3,12of12inf
86551,ZYMURGIES,86532,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,0,3,12of12inf
86552,ZYMURGY,86533,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,0,3,12of12inf

In [ ]:
pos_words = lm_dict[lm_dict["Positive"] != 0]["Word"].str.lower().to_list()
neg_words = lm_dict[lm_dict["Negative"] != 0]["Word"].str.lower().to_list()

pos_words[:10]

['able',
 'abundance',
 'abundant',
 'acclaimed',
 'accomplish',
 'accomplished',
 'accomplishes',
 'accomplishing',
 'accomplishment',
 'accomplishments']

In [ ]:
neg_words[:10]

['abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abandonments',
 'abandons',
 'abdicated',
 'abdicates',
 'abdicating',
 'abdication']

In [ ]:
df["n"] = df["text_clean"].apply(lambda x: len(x.split()))
df["n_pos"] = df["text_clean"].apply(
    lambda x: len([w for w in x.split() if w in pos_words])
)
df["n_neg"] = df["text_clean"].apply(
    lambda x: len([w for w in x.split() if w in neg_words])
)

df

,title,text,text_clean,n,n_pos,n_neg
0,raw_text_2022,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...,8244,75,353
1,raw_text_2023,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...,7565,68,337

In [ ]:
df["lm_level"] = df["n_pos"] - df["n_neg"]

df["lm_score1"] = (df["n_pos"] - df["n_neg"]) / df["n"]
df["lm_score2"] = (df["n_pos"] - df["n_neg"]) / (df["n_pos"] + df["n_neg"])

CUTOFF = 0.3
df["lm_sentiment"] = df["lm_score2"].apply(
    lambda x: "positive" if x > CUTOFF else "negative" if x < -CUTOFF else "neutral"
)
df

,title,text,text_clean,n,n_pos,n_neg,lm_level,lm_score1,lm_score2,lm_sentiment
0,raw_text_2022,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...,8244,75,353,-278,-0.033721,-0.649533,negative
1,raw_text_2023,Item 1A. Risk Factors\nYou should carefully c...,item risk factors you should carefully conside...,7565,68,337,-269,-0.035558,-0.664198,negative

# finBERT

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import scipy
import torch

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

In [ ]:
def finbert_sentiment(text: str) -> tuple[float, float, float, str]:
    with torch.no_grad():
        inputs = tokenizer(
            text, return_tensors="pt", padding=True, truncation=True, max_length=512
        )
        outputs = model(**inputs)
        logits = outputs.logits
        scores = {
            k: v
            for k, v in zip(
                model.config.id2label.values(),
                scipy.special.softmax(logits.numpy().squeeze()),
            )
        }
        return (
            scores["positive"],
            scores["negative"],
            scores["neutral"],
            max(scores, key=scores.get),
        )

In [ ]:
# Notice that this is the raw text, no preprocessing
df[["finbert_pos", "finbert_neg", "finbert_neu", "finbert_sentiment"]] = (
    df["text"].apply(finbert_sentiment).apply(pd.Series)
)
df["finbert_score"] = df["finbert_pos"] - df["finbert_neg"]

In [ ]:
df[
    [
        "title",
        "text",
        "finbert_pos",
        "finbert_neg",
        "finbert_neu",
        "finbert_sentiment",
        "finbert_score",
    ]
]

,title,text,finbert_pos,finbert_neg,finbert_neu,finbert_sentiment,finbert_score
0,raw_text_2022,Item 1A. Risk Factors\nYou should carefully c...,0.012042,0.896314,0.091644,negative,-0.884272
1,raw_text_2023,Item 1A. Risk Factors\nYou should carefully c...,0.060213,0.254696,0.685091,neutral,-0.194482

# llama

In [ ]:
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser

/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py:3553: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
!pip install langchain-community

Collecting langchain-community
  Downloading langchain_community-0.3.18-py3-none-any.whl.metadata (2.4 kB)
Collecting langchain-core<1.0.0,>=0.3.37 (from langchain-community)
  Downloading langchain_core-0.3.37-py3-none-any.whl.metadata (5.9 kB)
Collecting langchain<1.0.0,>=0.3.19 (from langchain-community)
  Downloading langchain-0.3.19-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.0.38)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (3.11.12)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (9.0.0)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community)
  Downloading pydantic_settings-2.7.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (0.3.8)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: numpy<2,>=1.26.4 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.18.3)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.6 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.19->langchain-community) (0.3.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain<1.0.0,>=0.3.19->langchain-community) (2.10.6)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.37->langchain-community) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.37->langchain-community) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.37->langchain-community) (4.12.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (3.10.15)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (0.23.0)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain-community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain-community) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain-community) (3.1.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.37->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.19->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<1.0.0,>=0.3.19->langchain-community) (2.27.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.125->langchain-community) (1.3.1)
Downloading langchain_community-0.3.18-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 47.5 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.0-py3-none-any.whl (7.8 kB)
Downloading langchain-0.3.19-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 38.6 MB/s eta 0:00:00
Downloading langchain_core-0.3.37-py3-none-any.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.7/413.7 kB 23.8 MB/s eta 0:00:00
Downloading pydantic_settings-2.7.1-py3-none-any.whl (29 kB)
Downloading marshmallow-3.26.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.2 MB/s eta 0:00:00
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: python-dotenv, mypy-extensions, marshmallow, httpx-sse, typing-inspect, pydantic-settings, dataclasses-json, langchain-core, langchain, langchain-community
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.3.35
    Uninstalling langchain-core-0.3.35:
      Successfully uninstalled langchain-core-0.3.35
  Attempting uninstall: langchain
    Found existing installation: langchain 0.3.18
    Uninstalling langchain-0.3.18:
      Successfully uninstalled langchain-0.3.18
Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.0 langchain-0.3.19 langchain-community-0.3.18 langchain-core-0.3.37 marshmallow-3.26.1 mypy-extensions-1.0.0 pydantic-settings-2.7.1 python-dotenv-1.0.1 typing-inspect-0.9.0

In [ ]:
from langchain_community.chat_models import ChatOllama

In [ ]:
# For handling errors
from tenacity import retry, stop_after_attempt, RetryError

In [ ]:
class SentimentClassification(BaseModel):
    sentiment: str = Field(
        ...,
        description="The sentiment of the text",
        enum=["positive", "negative", "neutral"],
    )
    score: float = Field(..., description="The score of the sentiment", ge=-1, le=1)
    justification: str = Field(..., description="The justification of the sentiment")
    main_entity: str = Field(..., description="The main entity discussed in the text")

In [ ]:
@retry(stop=stop_after_attempt(5))
def run_chain(text: str, chain) -> dict:
    return chain.invoke({"news": text}).dict()


def llm_sentiment(text: str, llm) -> tuple[str, float, str, str]:
    parser = PydanticOutputParser(pydantic_object=SentimentClassification)

    prompt = PromptTemplate(
        template="Describe the sentiment of a text of financial news.\n{format_instructions}\n{news}\n",
        input_variables=["news"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    chain = prompt | llm | parser

    try:
        result = run_chain(text, chain)

        return (
            result["sentiment"],
            result["score"],
            result["justification"],
            result["main_entity"],
        )
    except RetryError as e:
        print(f"Error: {e}")
        return "error", 0, "", ""